# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
nv=np.zeros(10)
nv

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
v=np.arange(10,49)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [4]:
print(v.shape)

(39,)


5. Print the type of the previous array in question 3

In [5]:
type(v)

numpy.ndarray

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/anaconda3\\Library\\inclu

7. Print the dimension of the array in question 3


In [7]:
print(v.ndim)

1


8. Create a boolean array with all the True values

In [8]:
bArray=np.ones((2,2), dtype=bool)
bArray

array([[ True,  True],
       [ True,  True]])

9. Create a two dimensional array




In [9]:
twoArr=np.arange(20).reshape(4,5)
print(twoArr)
print(twoArr.ndim)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
2


10. Create a three dimensional array



In [10]:
threeArr=np.arange(27).reshape(3,3,3)
print(threeArr)
print(threeArr.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
rev=np.arange(20)
print(rev)
np.flip(rev)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
nullV=np.zeros(10)
nullV[4]=1
nullV

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
im=np.identity(3)
im

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(np.float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print("arr1 > arr2")
print(np.greater(arr1,arr2))
print("arr1 < arr2")
print(np.less(arr1,arr2))
print("arr1 = arr2")
print(np.array_equal(arr1,arr2))

arr1 > arr2
[[ True False  True]
 [False  True False]]
arr1 < arr2
[[False  True False]
 [ True False  True]]
arr1 = arr2
False


17. Extract all odd numbers from arr with values(0-9)

In [17]:
a = np.arange((0),(9))
a[a % 2 == 1]

array([1, 3, 5, 7])

18. Replace all odd numbers to -1 from previous array

In [18]:
a[a % 2 == 1]= -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
x = np.ones((5,5))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1,1]=12
print(arr2d)


[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d [0,] =64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [30]:
arrtwoD=np.arange(9).reshape(3,3)
print(arrtwoD)
arrtwoD[0,]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [31]:
arrtwoD=np.arange(9).reshape(3,3)
print(arrtwoD)
arrtwoD[1,1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [40]:
arrtwoD=np.arange(0,9).reshape(3,3)
print(arrtwoD)
arrtwoD[0:2,2:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [57]:
import random
rand = np.random.random((10,10))
print(rand) 
randmin, randmax = rand.min(), rand.max()
print("Minimum and Maximum Values:")
print(randmin, randmax)


[[0.75517022 0.91795521 0.45609212 0.56975285 0.07453123 0.98755155
  0.41844773 0.32860539 0.4366048  0.72162062]
 [0.51657775 0.12751138 0.03824174 0.73656027 0.45096572 0.53582998
  0.13602985 0.15755852 0.97690345 0.8423365 ]
 [0.58327999 0.60085788 0.97008548 0.69063619 0.91549276 0.10350768
  0.17547345 0.64554798 0.38082281 0.27723092]
 [0.34030941 0.50525451 0.97766691 0.02032343 0.39022601 0.1552559
  0.93382138 0.70884975 0.30490712 0.9374731 ]
 [0.1231101  0.95144712 0.14594159 0.5252897  0.17367895 0.90890675
  0.05861364 0.49712368 0.40314137 0.47288987]
 [0.64824159 0.2220718  0.38692275 0.56260148 0.39418832 0.90995092
  0.9518171  0.15088497 0.42696001 0.38612363]
 [0.70831133 0.58966564 0.59478201 0.41122256 0.56716838 0.77103636
  0.60498478 0.50951462 0.36017345 0.14976178]
 [0.05139885 0.00131789 0.00460299 0.90435124 0.49595197 0.01554154
  0.50990051 0.91166891 0.8887628  0.41876171]
 [0.03541418 0.02721823 0.20566543 0.18466668 0.8069146  0.36456099
  0.7920103  

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [59]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [60]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where (a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [105]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names != 'Will'
data[names != 'Will']

array([[-1.19796879, -0.50984902, -1.39624699,  0.88782349],
       [-0.39121086, -0.01149952, -0.95963343, -0.5599256 ],
       [ 0.69463057,  0.57224397,  0.23034125,  0.48063763],
       [-0.02403861, -1.77991995, -0.65116396, -0.68354994],
       [ 0.17017792,  0.52789291, -2.21650925,  0.19599902]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [114]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
cond = (names != 'Will') & (names != 'Joe')
data[cond]

array([[ 0.02992493,  1.44146481,  0.41272153, -2.34429614],
       [-0.3912647 ,  1.95953882, -1.04348318,  2.06455185]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [118]:
arr = np.random.uniform(low=1.0, high=15.0, size=(5,3))
print(arr)

[[ 4.95594161  1.45857627  5.27016007]
 [13.04137529  7.50771763  1.92732173]
 [ 8.54542325  8.57960583 14.66746293]
 [ 3.57807343 13.0907481  10.85905872]
 [11.83933741 14.35656287 13.99723796]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [129]:
arr_1 = np.arange(1,17,dtype=float).reshape(2,2,4) 
print(arr_1)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


33. Swap axes of the array you created in Question 32

In [130]:
arr_1.swapaxes(1,2)

array([[[ 1.,  5.],
        [ 2.,  6.],
        [ 3.,  7.],
        [ 4.,  8.]],

       [[ 9., 13.],
        [10., 14.],
        [11., 15.],
        [12., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [156]:
arr = np.arange(10)
a= np.sqrt(arr)
print(np.where(a <0.5, 0, a))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [191]:
print ("First array")
x = np.random.randn(12)
print(x)

print ("Second array")
y = np.random.randn(12)
print(y)

print ("Maximum of both arrays")
np.maximum(x,y)


First array
[ 0.64659394  0.41853289  0.71482064 -0.90986133  0.49162025  0.61749692
 -1.35698959  0.21587704 -0.09656912 -0.84991364 -0.42477045  0.08310069]
Second array
[-1.6553013  -0.46129831  0.37222211 -0.16280102 -1.77214584 -0.05778086
 -1.43914582  1.26478703 -0.11570571  0.99426477  0.84891132  0.3923799 ]
Maximum of both arrays


array([ 0.64659394,  0.41853289,  0.71482064, -0.16280102,  0.49162025,
        0.61749692, -1.35698959,  1.26478703, -0.09656912,  0.99426477,
        0.84891132,  0.3923799 ])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [193]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
sorted(set(names))

['Bob', 'Joe', 'Will']

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [211]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [228]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([10,10,10])
sampleArray[:,1:2]=10
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [229]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [236]:
matrix = np.random.randn(20)
print(matrix)
np.cumsum(matrix)

[ 0.05215497  0.4777185  -0.93627156 -0.42879586  1.17017628 -1.52725007
  1.24588809  2.43271935  0.07651555  0.01988454  0.43448927  0.48189549
 -0.22362582 -0.79893647 -0.04787179  0.88544115 -1.23621249 -0.21127631
 -0.75952151  1.34379523]


array([ 0.05215497,  0.52987347, -0.40639809, -0.83519396,  0.33498233,
       -1.19226775,  0.05362034,  2.4863397 ,  2.56285524,  2.58273978,
        3.01722906,  3.49912455,  3.27549872,  2.47656225,  2.42869046,
        3.31413162,  2.07791913,  1.86664282,  1.10712131,  2.45091654])