# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
arr = np.arange(10)
print(arr)
arr2 = np.reshape(arr,(2,5))
arr2

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [20]:
arr1=np.arange(10).reshape(2,5)
arr2=np.ones((2,5),dtype=int)
arr2
verticalStack=np.vstack((arr1,arr2))
verticalStack

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [22]:
horizontalStack=np.hstack((arr1,arr2))
horizontalStack

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [49]:
print(arr1)
arr1.flatten()

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [73]:
arr0=np.arange(15).reshape(3,5)
print(arr0)
arr0.ravel()



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [85]:
ab = np.arange(15)
ab.resize(5,3)
ab

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [88]:
sq = np.arange(25).reshape(5,5)
np.square(sq)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [105]:
mn = np.arange(30).reshape(5,6)
print(mn)
print("Mean of the array is:",np.mean(mn))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Mean of the array is: 14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [95]:
mn.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [97]:
np.median(mn)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [99]:
mn.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [121]:
dg = np.arange(16).reshape(4,4)
print(dg)
print("The sum of the diagnol elements is:", np.trace(dg))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
The sum of the diagnol elements is: 30


## Question:13

### Find the determinant of the previous array in Q12?

In [122]:
np.linalg.det(dg)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [123]:
prt = np.arange(100).reshape(10, 10)

print("5th percentile of arr : ", 
       np.percentile(prt, 5))
print("95th percentile of arr : ",
       np.percentile(prt, 95))

5th percentile of arr :  4.95
95th percentile of arr :  94.05


## Question:15

### How to find if a given array has any null values?

In [144]:
hasNull=np.array ([[1,3,None,4,55,23]])
print("The array has null values" ) if None in hasNull else print("The array has no null values")


The array has null values
